WorldBrain/Memex

package.json, src/omnibar.js, src/overview/components/Overview.jsx, src/overview/enhancer.js, src/overview/index.js, src/overview/store.js, src/util/redux-query-sync.js
Sorry, also had to create this new PR for the same reason (deleted fork).
When user selects search result this now checks whether the selected result is a suggested url or a default suggestion (which includes search query). If the selected result is a search query it then opens the overview.html and adds the search query as a url variable (named "q").
I've cherry picked Treora's commit that implement redux-query-sync. His code now replaces my old check for url variables inside of Overview component and it's now removed in last commit.
=> Link first result in omnibar to overview page. Closes #8.

package.json, src/overview/components/Overview.jsx, src/overview/components/ResultList.jsx, src/overview/selectors.js, src/util/ordered-group-by.js, src/util/safe-nested-access.js
Main idea (discussed in issue #28) is to group results state by URL (later group by page doc, depending on the outcome of #17) and only display the latest results in those groups. Essentially just selector/state derivation logic + container state->view mapping logic. 
So far have implemented the main state derivation logic:
- custom groupBy-type fn, inspired by lodash's `groupBy`, which also preserves the ordering of the input collection by outputting an array of arrays (array of ordered groups)
- safe access to deep nested object values helper fn (used as the `iteratee` input to the ordered `groupBy`)
- selector derivation logic using those generically-written fns + state shape mapping to form the search results state
Now need to write container logic to map the search results state to …
=> Only show latest visit. Closes #28

extension/manifest.json, extension/popup.css, extension/popup.html, gulpfile.babel.js, package.json, src/background.js, src/options/containers/settings/index.jsx, src/options/preferences/actions.js, src/options/preferences/components/Preferences.css, src/options/preferences/components/Preferences.jsx, src/options/preferences/constants.js, src/options/preferences/container.js, src/options/preferences/enhancer.js, src/options/preferences/index.js, src/options/preferences/reducers.js, src/options/preferences/selectors.js, src/options/store.js, src/page-storage/cleanup.js, src/popup.js, src/popup/archive-button.js, src/popup/index.js, src/popup/search-input.js, src/scheduled-tasks/background/freeze-dry-cleanup.js, src/scheduled-tasks/background/index.js, src/scheduled-tasks/index.js, yarn.lock
Main things to do:
Part 1 is simple. UI done for a checkbox in settings to allow user to set a flag in local storage. Implementation of this being done in #46 
Part 2 will involve a new button in popup. The button action should set a flag, say `keepFreezeDry`, on the page doc associated with the current page*. This flag will be used in part 3. Harder part is keeping the state of that button set (it's essentially a toggle); popup is in plain JS + HTML.
\* _There is no guaranteed way to get the current page. It will have to do a query on page docs with the same URL and take the latest, I guess._
Part 3 is by far the most difficult part. I'm currently thinking a scheduled task every hour (?) to remove freeze-dry attachments from all page docs that are not:
- the latest 100 page docs
- pages …
=> Limit freeze dry versions. Closes #42

src/overview/actions.js, src/overview/components/DeleteConfirmation.css, src/overview/components/DeleteConfirmation.jsx, src/overview/components/Overview.jsx, src/overview/components/VisitAsListItem.jsx, src/overview/reducer.js, src/overview/selectors.js, src/page-storage/deletion.js
Issue #16 
Mostly set up and working. Three choices when the user clicks the trashcan:
- delete just the visit
- delete the visit and associated docs (page, other visits to URL)
- cancel
Currently the associated docs choice just deletes the page if it's an orphan (no other visits pointing to it). 
TODO: 
Could improve the styles a bit.
[How it looks/works now](https://media.giphy.com/media/xUA7aLCBr26PE7cL60/giphy.gif)
=> Delete visit + assoc docs prompt. Addresses #16

src/background.js, src/imports/background/imports-preparation.js
In reference to #39 
Hope I added it in the correct file :sweat_smile:
=> Added bookmark creation listener

src/overview/components/DateRangeSelection.jsx
Addresses point 1 in #94 and point 3 in #108.
Main behaviour change is calling [`moment.endOf('day')`](https://momentjs.com/docs/#/manipulating/end-of/) when updating `endDate` state; this makes it inclusive of the entire day rather than default.
=> Change behaviour of endDate date picker to be inclusive of day

package.json, src/background.js, src/omnibar.js, src/popup/container.js, src/util/nlp-time-filter.js, yarn.lock
`tldjs` package was used for checking validity of URLs when:
- opening Overview (decide to open in new or current tab)
- pressing enter in omnibar on WorldBrain search (decide if input is a URL, and nav to that URL if so, else append input as query string to Overview URL)
The package is more suited for work with domain-specific stuff however, hence was a bit weird for use here. Often resulted in false positives with `domain.tld`-like patterns (which we use in our search query "language") as seen in #111.
Replaced with `url-regex` package, which we are already using in other parts, which seems to be much more appropriate for in these two cases.
May bring `tldjs` back later; useful for domain-specific stuff.
=> Move URL checks away from `tldjs` - fixes #111

src/overview/components/PageResultItem.jsx
In the current version when we click on the result in overview page it open open in current tab, when user wants to go again on overview page the result again fetch.
This pull request contains open in new-tab when we click on the result.
=> Open new tab after click on result in overview

src/page-analysis/background/fetch-page-data.js, src/page-analysis/content_script/extract-pdf-content.js
- Also added the pdf extractor to the transform-text pipeline
@oliversauter The fact that the pdf-extractor for websites we visit wasn't being run through the pipeline may have been a reason for some of the terms not being removed when expected.
=> Fixed the bug causing imports to fail on pdf's

src/activity-logger/index.js, src/imports/background/import-estimates.js, src/imports/background/import-item-processor.js, src/imports/background/imports-connection-handler.js, src/imports/background/index.js, src/options/imports/reducers.js, src/util/map-set-helpers.js
Import item list (also used for deriving estimate counts) now stored as `Map` of normalized + encoded URLs -> import items. Previously was `Array` of import items.
- custom Pouch.find queries moved to standard Pouch.allDocs queries
- normalization on import item keys means a lot of semantically-identical (in our context) URLs will now be properly filtered out
- bookmarks and history counts should make more sense for users (proper distinction made). Old ext imports is still a bit of an odd-case as each old-ext import will increase either the history or bookmark AND old-ext "already saved" count
- put concurrency setting back into imports processor (currently set at 3 items at any time). Concurrency queue implemented a bit back should guarantee safety at DB-level for indexing, allowing us …
=> Import estimates/items list derivation improvements

src/bookmarks/background/deletion.js, src/omnibar.js, src/overview/components/PageResultItem.jsx, src/overview/container.js, src/overview/selectors.js, src/search/index.js, src/search/map-search-to-pouch.js, src/search/search-index/add.js, src/search/search-index/pipeline.js, src/search/search-index/util.js
Search has been changed as described in the last bit of [this comment in #150](https://github.com/WorldBrain/WebMemex/pull/150#issuecomment-341942562). 
Simply: latest visit *should* always be used for search unless no visits exist for a page (only then bookmark is used).
Make sure to remove all existing data before trying this branch.
=> Change latest event timestamp behaviour in search

src/page-storage/deletion.js, src/popup/container.js, src/pouchdb.js, src/search/index.js
- fixes #177 
- deletion module regressed after being forgotten during recent data model changes (new index)
- now rewritten to work by grabbing the domains index entry and deleting all pages in that (+ lookups to get all assoc. meta docs for Pouch deletion)
=> Fix delete-by-domain functionality

src/search/search-index/search.js
- previously did search on either bookmark OR visit indexes (oversight in PR #155)
- now in the case of bookmarks filter, only searches bookmarks index, but in the case of standard search, makes sure to search both
- fixes #181
=> Update time filter back search logic for bookmark filter

src/search/index.js, src/search/search-index/search.js
- found this mistake on `dev/playing-with-static-index-values` branch after indexing about 4000 docs and wondering why search time seemed to increase linearly
- one of the final search stages takes the results and does the reverse index lookups to associate them all with their reverse index docs (contains data about latest timestamp, assoc. visits/bookmarks data, etc, all used to derive display state)
- the amount of lookups can be reduced dramatically by doing the pagination stage before lookup stage (__obviously__)
- pagination always leaves us with a constant number of lookups needed: `PAGE_SIZE` docs (10 or 5, depending on UI)
- previously was `N` number of lookups (where `N` is the size of the entire set of pages matched to the query)
- this will change if we go ahead with static …
=> Fix unneeded search lookups in final stage of search

src/search/search-index/index.js, src/search/search-index/search.js, src/util/priority-queue.js
- fixes #186 
- we don't really need a proper priority queue, we can get away with just pushing all search requests to the front of the internal data structure, keeping all other existing behaviour
- search will still always wait for the currently running job to finish, which could take a few seconds if a big page (still much better than waiting behind lots of them!)
=> Allow search requests highest priority in index queue

src/overview/actions.js, src/overview/components/Overview.css, src/overview/components/PageResultItem.jsx, src/overview/components/ResultList.jsx, src/overview/components/ResultsMessage.js, src/overview/container.js, src/overview/reducer.js, src/overview/selectors.js
- fixes #200 
- just needed some extra state for overview UI, update to an existing view, and additional parameter to send to backend search request
- TODO: make the state derivation determining when to show the count message wait until search has changed before showing (e.g., don't show count on blank search, but if you enter terms/time filter it should come up and wait for the new results - now it shows instantly due to React rerendering on prop change)
=> Show total search count in overview

src/background.js
- fixes #206 
- make sure to wait for async blacklist stuff to finish before doing the other stuff (like opening the welcome page)
- bigger issue than reported as: if the user interacts with the empty blacklist, they will never get the default entries
- always been a hard bug to reproduce, but this seems to fix it for me (installed ~15 times and have no encountered it); report if still able to reproduce
=> Fix default blacklist entries sometimes not being set

src/imports/background/import-item-processor.js
- relates to an idea from this comment: https://github.com/WorldBrain/Memex/issues/143#issuecomment-349243147
- at start of import process for each import item (before any expensive XHR or indexing logic performed), grab all `VisitItem`s from WebExt History API and filter out the items where `TransitionType` is not of interest in our context
- if there's no items left post-filtering, "Redirection URL" Error gets thrown, allowing the current item to be skipped over
- also in the later "`VisitItem` to visit doc" mapping stage, only those `VisitItem`s with wanted `TransitionType`s will be mapped to ensure consistency
- docs for ref on these types:
- `history.VisitItem`: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history/VisitItem
- `history.TransitionType`: …
=> Skip import items where TransitionType of all visits not wanted 

src/search/search-index/add.js, src/search/search-index/util.js
Discussion in #187 prompted me to look more into the indexing algo to find slowdown on larger pages (this page is a good example with ~6.5k terms: https://en.wikipedia.org/wiki/United_States - takes me ~90s to index the terms with 6k pages in my DB). After putting some timers around the place, it was pretty clear the main slowdown was from the lookup of existing terms ([this line](https://github.com/WorldBrain/Memex/blob/master/src/search/search-index/add.js#L80)). Specifically it does N lookups for N terms.
For pages with large amount of terms, it can take a while to do all the queries and get all this data back. This change makes a decision based on the # of terms needed to index whether to do a single range lookup over the entire terms index vs doing the N individual lookups. For large …
=> Range lookup during terms indexing for pages with large amounts of terms

src/bookmarks/background/addition.js, src/bookmarks/background/deletion.js, src/bookmarks/background/index.js, src/overview/actions.js, src/overview/components/PageResultItem.jsx, src/overview/container.js, src/page-storage/deletion.js, src/popup/container.js, src/search/index.js, src/search/search-index/add.js
- fixes #218 
- new bookmark-only adding method on search-index interface (assumes existence of assoc. page - 3ee4199)
- bookmark removal code cleaned up + missing docs added + minor logical bug fixed with orphan page cases (overall flow remains unchanged, however - 69efc43)
- UI state actions for bookmark toggle button in Overview cleaned up a bit (41ef856)
=> Bookmarking via Overview UI without page content reindexing

src/search/query-builder.js
- subdomains indexed correctly (eg `gist.github.com`), separate of the root domain entry (eg `github.com`), however the query-builder pattern used to attempt extraction of domain strings from user input doesn't check subdomains
- pattern updated to have optional clause for checking subdomain in the string
- pattern also updated to include hyphen character `-` in domain detection (not in alphanumeric character class `\w`)
Kind of related:
- if you search for a root domain (eg. `github.com`), should pages indexed under related subdomains (eg. `gist.github.com`) also appear in results?
Makes sense to me, but may be quite difficult to implement. One thing we could do is: when indexing a page, if subdomain detected (`gist.github.com`), index the page under __both__ the subdomain + root domain …
=> Add support to query-builder for subdomains

src/overview/components/DateRangeSelection.jsx, src/util/nlp-time-filter.js
- fixes #255 
- `before:""` and `after:""` syntax in the omnibar updated to be case insensitive and also not worry about single or double quotes
- NLP queries typed into the overview time filters no longer get resolved into date strings for display; they stay as the entered NLP query
@oliversauter what about when you type something like `test before:"now"` in omnibar and press enter to go to the overview page for that search? At the moment, as we don't have support for NLP queries in the URL state, it will auto-resolve to the timestamp of the query and build the overview URL state using that (so the date picker value will be set to "2018-10-01", or whatever resolved date, rather than the text "now")
=> NLP query behaviour changes

__mocks__/src/pouchdb.js, src/util/delay.test.js, src/util/event-to-promise.test.js, src/util/make-range-transform.test.js, src/util/nice-time.test.js, src/util/pouchdb-update-doc.test.js, src/util/random-string.test.js, src/util/short-url.test.js, src/util/sync-location-hashes.js, src/util/sync-location-hashes.test.js, src/util/tab-events.test.js, src/util/tree-walker.test.js, src/util/webextensionRPC.test.js
[Refs](https://github.com/WorldBrain/Memex/issues/102)
Some of the tests in this module are coded to be skipped due to some technical issues at the jest repository. [Refer](https://github.com/facebook/jest/pull/4884). Although it will be fixed once we upgrade to Jest22.
I would like to clear some doubts regarding the general construction of the testing suite.
* Is the following style of test structure appropriate?
```
describe('[moduleName]', () => {
test('should [describe behaviour]', () => {
})
})
```
* Again, to rediscuss the issue of having tests in their own directory of ```__tests__``` in comparison to having them beside the module?
* In this PR I have written a combination of Positive and Negative tests. Would the devs like to follow the Positive style of testing or the …
=> Tests for Util Module

src/activity-logger/background/index.js, src/activity-logger/background/log-page-visit.js, src/activity-logger/background/scroll-state.js, src/activity-logger/background/tab-manager.js, src/activity-logger/background/tab-time-tracker.js, src/activity-logger/content_script/index.js, src/activity-logger/content_script/scroll-state-fetchers.js, src/page-analysis/background/index.js, src/search/index.js, src/search/search-index/add.js, src/search/search-index/util.js
- fixes #231
- adds new metadata to indexed visits based on states accumulated over the course of the visit:
- `duration: number`: time in ms associated tab was active during that visit
- `scrollPx: number`: pixel user was scrolled to at end of visit
- `scrollPercent: number`: percentage of page user was scrolled to at end of visit
- `scrollMaxPx: number`: furthest pixel user scrolled to during entire visit
- `scrollPercent: number`: furthest percentage of page user scrolled to during entire visit
- new background script tabs state that keeps track of active states, active times, scroll states (derives from DOM data sent from running content scripts when user scrolls), scheduling page analysis
- a lot of inspiration for the logic behind keeping track of tab active states to derive active …
=> Visit interactions data

src/common-ui/components/TagRow.js, src/common-ui/components/Tags.css, src/common-ui/components/Tags.js, src/common-ui/containers/TagsContainer.js, src/overview/actions.js, src/popup/components/Popup.css, src/search/query-builder.js
Fix bugs that are discussed in #260
=> Fix bugs in tagging-ui

src/page-analysis/background/index.js, src/page-analysis/content_script/extract-page-content.js, src/search/search-index/pipeline.js, src/util/transform-page-text.js
- page text content goes through two main stages: 1) HTML preproc -> 2) plain-text preproc
- previously storing result of 2) at path `content.fullText` in page docs - pretty much the same content as will go into the terms index
- now storing result of 1) in page docs, while terms index source remains unchanged
- language, extracted from the DOM, is also used in 2), although only available from the source data of 1) - now simply adding that as an additional `content.lang` key in the page doc for access in 2)
- seems to be functional in both importing and page visit scenarios
=> Store unprocessed page text content in page doc

src/page-analysis/background/fetch-page-data.js, src/page-analysis/background/index.js, src/page-analysis/content_script/extract-page-content.js, src/page-analysis/content_script/page-metadata-rules.js, src/search/search-index/add.js
Fixes part of #225 - titles and some other metadata content was being extracted wrong on certain dynamic sites (`qz.com` given as example).
As URL state changes, new page visits and recording happens, but as our data extraction rules was giving priority to certain parts of the DOM that are not commonly updated with other dynamic content (OG tags - meant for single-visit bots, like FB bot), extracted titles and other content were not correct.
These changes update the fathom rules used to extract the needed data - prioritise parts of the DOM that face standard user rather than bots.
Would be good to get examples of other sites with dynamic URL state updates from general interaction, to test with.
Other minor cleanups and added missing docs - this part of codebase not touched in a while.
=> Update page metadata extraction rules

src/activity-logger/README.md, src/activity-logger/background/index.js, src/activity-logger/background/log-page-visit.js, src/activity-logger/background/tab-manager.js, src/activity-logger/background/tab-state.js, src/bookmarks/background/addition.js, src/imports/background/import-item-processor.js, src/page-analysis/background/index.js, src/page-storage/store-page.js, src/search/index.js, src/search/search-index/add.js, src/search/search-index/pipeline.js, src/search/search-index/search.js, src/search/search-index/tags/index.js, src/search/search-index/util.js, src/util/pausable-timer.js, src/util/tab-events.js
- fixes #232 
- description of new page visits process in 8cbda3d
- a lot of cleanup of modules related to the page visit process (`log-page-visit`, `store-page`, `page-analysis`)
- new index method for stage ii allowing updating just the terms for an existing page
- removal of unused pouch visits during page visit process
- cleanup of index pipeline code, and allowing it to work with no main terms content (stage i)
- update of terms search implementation to merge in title/URL terms results with content terms results
- implementation of new `PausableTimer` class: state wrapper around `setTimeout` (7b8c4c9)
TODO/enhancements:
=> Initial page visit indexing

src/util/transform-page-text.js
- now words with >= 30 chars should make it through our text preprocessing pipeline for indexing and querying
https://worldbrain.slack.com/archives/C9297H925/p1518429732000487?thread_ts=1518402101.000107&cid=C9297H925
=> Increase 20 word char limit in preproc to 30

src/page-analysis/background/fetch-page-data.js, src/util/encode-url-for-id.js
- fixes #293 
- `fetch-page-data` module had a bug returning nothing in the case of PDFs; should have returned an object that allows running and cancelling the XHR
- our PDF checking logic is terrible also: it simply checks if the URL ends with ".pdf" - this won't work if the URL has query or hash states, or if the URL doesn't even end in ".pdf" but still responds with a PDF
=> Fix bug with PDFs not working in imports

src/activity-logger/background/index.js, src/manifest.json
- fixes #291
- apparently that "easiest" option I mentioned in that issue yesterday isn't supported in FF. Doesn't matter too much, just add a quick check to page/tab logging condition to see if current tab is incognito or not
- works on both FF and Chrome
=> Ignore page logging in incognito mode

src/overview/actions.js
- if you scroll down a few pages, then put some text in, the page state will be reset, but the immediate next search will still use all the old page state (hence skip the first X results)
- fixes when the state is sampled
- [found](https://github.com/WorldBrain/Memex/pull/287#issuecomment-365109944) by @oliversauter
=> Fix up out-of-date state when deriving search params

src/imports/background/import-item-creation.js
- happens if one week of history has < 30 usable items, and the next week exceeds the total count
- this should keep it at the 30 limit in those cases
=> Fix history edge case where onboarding import limit can be exceeded

gulpfile.babel.js
- explicitly `process.exit(1)` when any bundle's browserify stream emits a build error
- only in standard build; watch/dev mode shouldn't exit the process
- also only printing out the stack trace now - should have done that ages ago
- should ensure CI build fails on JS build failure
=> Quick fix to kill gulp process when a bundle build fails

docs/Contributing-Guide.md
- repeated these instructions to a few contributors now; might as well write
them down as it is a common task, as well as a suggested way of keeping in syncing
- updated all the old links when our repo was called WebMemex
- removed a section about Windows-specific instructions as it was just the same command
=> Added "Creating branches" instruction section in contrib guide

src/activity-logger/content_script/index.js
- reported in #325 that failed connections between content script and bg script spam the page console (content_script loaded as part of web page)
- can only reproduce on [untracked tabs](https://github.com/WorldBrain/Memex/issues/314#issuecomment-367879824)
- now any Promise rejections are caught and ignored, rather than default uncaught Promise behaviour of logging error to stderr - not optimal for content_script
=> Ensure any content script scroll msg errors are caught

src/page-analysis/content_script/extract-page-content.js, src/search/pipeline.test.data.js, src/search/pipeline.test.js, src/search/search-index-new/pipeline.js, src/search/search-index-old/pipeline.test.js, src/search/util.js, src/util/transform-page-text.js
Fixes #330 
So far two stages mentioned in that issue have been removed and tests updated to verify the change works and doesn't effect other stuff.
Updated the pipeline tests in general to ensure both the current and slightly changed (type sig) new pipeline are both being tested. Fixed one issue from that. 
Some others remain that would be nice to get fixed with this work:
- empty string can sometimes get through and be indexed (sometimes happens in current index too)
- stopwords can sometimes get through and be indexed
It's pretty strange that it seems like only "sometimes", and cannot reproduce in the tests (so far, could try some more test data), so need to look over all the pipeline-interacting code and see how these could get through. Also have the URLs, so could manually try and …
=> Simplify text pre-processing

gulpfile.babel.js, package.json, src/manifest.json, yarn.lock
Adds these Gulp commands:
- publish-extension (which calls the following two commands)
- publish-extension:chrome
- publish-extension:firefox
They need the following environment variables (so this data doesn't go into a public Git repo  ;)  ):
- AMO_API_KEY (Addons Mozilla)
- AMO_API_SECRET
- WEBSTORE_TOKEN_CODE
- WEBSTORE_EXTENSION_ID
- WEBSTORE_CLIENT_ID
- WEBSTORE_CLIENT_SECRET
The code is all untested, would be great to test with a fake app. This branch does give me a weird error when doing 'gulp lint':
```
TypeError: Error while loading rule 'react/jsx-uses-react': Cannot read property '1' of null
at Object.getFromContext (/home/vincent/Documents/Develop/Web/WorldBrain/Memex/node_modules/eslint-plugin-react/lib/util/pragma.js:34:21)
at Object.create …
```
=> Gulp commands for automated publishing

src/overview/onboarding/actions.js, src/search/search-index/search.js, src/search/search-index/util.js
Realized our URL and title terms index searches have been broken after looking into issue noted by @oliversauter on slack (great find!):
>When I go on this page: 
> https://worldbrain.helprace.com/i43-indexation-is-stopped-can-t-restart#comment-33385
> It finds it for “design community”, whereas ‘design’ is not in the text, and only ‘community’ is in the title. Searching for ‘design’ alone does not bring up the page.
Main commit:
- it was not ANDing properly on title and URL terms search
- it should do exactly the same thing for all 3 terms indexes, apart from score boosting, so now made sure it does
=> Fix current boosted terms search behaviour

src/util/update-notification.js
- buttons aren't supported in FF notifs; error gets thrown
- this is documented: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/NotificationOptions
- this button also just did the same thing as notif click
=> Fix update notifs in Firefox

setupJest.js, src/search-injection/constants.js, src/search-injection/utils.js
- quick google-specific fix for now (only thing we support anyway)
- checks the `tbm` query param which represents different google search types (they all run on same route)
- if it's set to an unwanted type, don't return a match in the main `matchURL` function
- should now only show on the "All" type of search (standard google text search)
- @digi0ps would be good to get you to review these changes (can't assign you via GitHub for some reason)
=> Fix rendering search results on all Google search types

src/background.js, src/options/settings/components/Checkbox.js, src/options/settings/components/SearchInjection.js, src/options/settings/components/SearchInjectionContainer.js, src/search-injection/components/ResultItem.css, src/search-injection/components/ResultItem.js, src/search-injection/components/Results.css, src/search-injection/components/Results.js, src/search-injection/components/container.js, src/search-injection/constants.js, src/search-injection/content_script.js, src/search-injection/dom.js, src/search-injection/utils.test.js
Thanks to @heliostatic's for his base work. :) 
Forked from #352. 
- Injected Memex results into DuckDuckGo and prettified.
_Above_
_Side_
- Added DuckDuckGo tick to the Settings
_By default they are both ticked_
> A suggestion would be to move Memex results after the extended filter bar (class=search-filters-wrap) and before the results list
Possible, but would require the box to appended differently into google and ddg container. Is it necessary?
@oliversauter @poltak
=> Show Memex results in DuckDuckGo.

package.json, src/search-injection/components/container.js
- seems like the local storage setting functions, called when the user removes/undos results, weren't updated to the new shape introduced with DDG support (still using the "google-only" shape)
- updated it to make sure to just update the persisted state of the current search engine within the stored object (search engines => bool flags)
Looking at this now, it is super obvious, and really should have been picked up in all the reviews and manual testing we all did on #362. That's the way things go sometimes, I suppose 😄 at least only a small fix needed.
Note that effected users - those who have pressed "remove results" on google/ddg - will now have the wrong state shape stored in local storage, but @digi0ps migration code should catch this and convert it over when we push the next update …
=> Fix Google/DDG search UI persisting incorrect state shape

src/search-injection/content_script.js, src/search/search-index-old/map-search-to-pouch.js, src/search/search-index-old/pipeline.js
- bug with the old index shaping pouch docs slightly differently depending on use-case
- title meant to be stored on `content.title`, but some new docs would also get it store on `title`
- the search would only check `title`; this leads to missing titles in search results (even though the data is still there in `content.title`)
- now ensuring all pouch add/update logic saves title only to `content.title`
- search-pouch mapping now falls back to `title`
- also set an explicit limit on the search-engine injection search request; we were asking for 2x the needed results before (display only shows 4/5)
=> Fix inconsistency in Pouch doc title path

package.json, src/search-injection/components/Dropdown.js, src/search-injection/components/Results.js, src/search-injection/components/container.js, yarn.lock
When *Dropdown* component is mounted, it attaches an eventListener to the document which sets the `dropdown` state to `false`, which closes the dropdown.
When the *Dropdown* component is unmounted the eventListener is removed. 
Is there any better method for this? 
@poltak @oliversauter @ShishKabab
=> Close Search Injection dropdown when clicked outside.

src/search-injection/components/ResultItem.js
- in some cases, where a page's title cannot be extracted (most websites work fine, PDFs depend on how the pdf metadata was set up) overview results will fallback to displaying URL for title
- search injection result views didn't have this fallback, leading to minor inconsistencies and not being able to click the result
=> Allow google/DDG results to fall back to URL if no title

package.json, src/activity-logger/background/index.js, src/activity-logger/background/log-page-visit.js, src/activity-logger/background/tab-change-listeners.ts, src/activity-logger/background/tab-manager.js, src/background.js, src/common-ui/components/Overlay.js, src/options/acknowledgement/components/content.jsx, src/options/acknowledgement/components/styles.css, src/options/options.jsx, src/options/store.js, src/overview/container.js, src/overview/enhancer.js, src/overview/onboarding/actions.js, src/overview/onboarding/reducer.js, src/overview/overview.jsx, src/overview/store.js, src/popup/popup.js, src/util/raven.ts, src/util/storage-changes.test.ts, src/util/storage-changes.ts, yarn.lock
- fixes #378 by adding redux middleware to our redux apps (overview + options) which snapshot UI state for error reports 
- also adds sentry support to the background script (missing)
- some quick fixes for some minor UI-related errors showing up in sentry (932c1ea)
TODO: 
@oliversauter distantly related: where does sentry fall under our privacy policy? From what I can see, as of current production version, any error will get sent to sentry with user information regardless of the opt-out preference on the privacy page
=> Misc. sentry additions + fixes

src/popup/components/Search.js
- fixes it now in Chrome
- FF currently breaks this, but apparently will be fixed in FF60: https://bugzilla.mozilla.org/show_bug.cgi?id=1324255
=> Ensure popup search input is auto-focused

gulpfile.babel.js
- missing `failAfterError` option in CSS watch task's `gulp-stylelint` setup; it defaults to `true`
=> Ensure stylelint does not fail watch build on error

src/activity-logger/background/index.js, src/analytics/analytics.js, src/options/imports/enhancer.js, src/options/imports/reducer.js, src/page-analysis/content_script/extract-fav-icon.js, src/search/background/index.js, src/search/search-index-new/models/fav-icon.ts, src/search/search-index-old/bookmarks/add.js, src/search/search-index-old/util.js
- most of these address errors relating to uncaught errors in the old index implementation (apparently we still have users on the old index)
- one issue fixed up in the options script which should address #390 #384 + #380. Options page could crash under the conditions: 
- user has gone to imports page prior to our removal of old extension migration (I think it was in the new index release)
- user comes back to imports page after updating (local storage contains the old data still, and imports UI attempted to rehydrate state using that)
- one non-sentry related enhancement added which is the removal of de/serialization of imports UI state:
- prev was serializing all UI state to a string before persisting to local storage
- this could have contributed to the imports UI performance issues …
=> Misc sentry fixes

.gitignore, build/config.js, build/env.js, build/loaders.js, build/minimizers.js, build/plugins.js, build/static-files.js, package.json, src/manifest.json, webpack.config.babel.js, yarn.lock
I thought I could keep adding things to the branch and they would automatically show up in #403. Seems like I have to open a new PR. Copy and pasted TODO list from last PR:
__\* _are "nice-to-have"s but lower prio and may not be possible___
Feel free to request or suggest more build features!
=> Webpack production build

src/direct-linking/background/storage.ts, src/search/search-index-new/storage/dexie-schema.ts, src/search/search-index-new/storage/manager.test.ts, src/search/search-index-new/storage/manager.ts, src/search/search-index-new/storage/registry.ts, src/search/search-index-new/storage/types.ts
@ShishKabab would be good to get your review + opinions on these changes before going ahead and bringing them in.
Notable changes (more info in commit messages):
1. ~~removed `pk` bool field from collection `fields` definitions~~ (moved to `IndexDefinition`)
- currently only ever used for ordering the indexable fields in Dexie schemas, however indexable fields in StorageManager are already declared in an ordered data structure
- only relates to indexable fields, but was declared as part of general data `fields` schema; need to handle case of user declaring field as PK but never declaring it in `indices`
- instead have taken inspiration from Dexie schemas by saying the first `indices` element is the primary key index (JSDoc added to typings to guide users when writing schemas)
- updated …
=> Compound index support for StorageManager

src/analytics/internal/analytics.js, src/search/search-index-new/storage/dexie-schema.ts, src/search/search-index-new/storage/index.ts, src/search/search-index-new/storage/types.ts
This branch has been updated to use the new `IndexDefinition` shape from #422. Currently it generates the same original Dexie schema that seems to work fine with existing data now 😃 
@ShishKabab I realized just for the task of porting the schemas, we won't have to worry about things like the additional full-text search indexes created from `'text'` fields and similar things - they are currently handled as part of the `StorageManager`'s `putObject` method which the existing data model isn't using yet. Moving the current `search-index-new` interface to `FeatureStorage` classes will be another, more-involved task todo down the road (maybe when we get rid of `search-index-old` feature module?). 
I have had to add a few new `FieldType`s. See what you think:
- `int`: integer numbers
- `float`: …
=> Port Dexie-based schema to StorageManager schemas

src/analytics/internal/analytics.js, src/search/search-index-new/storage/dexie-schema.ts, src/search/search-index-new/storage/index.ts, src/search/search-index-new/storage/manager.test.ts, src/search/search-index-new/storage/manager.ts, src/search/search-index-new/storage/registry.ts, src/search/search-index-new/storage/types.ts
This adds in a fix for a StorageManager bug I talked with @ShishKabab about on slack yesterday. The wrong field was being indexed for indexed fields of type `'text'`. 
This sadly affects all our users who upgraded to our direct linking release and will need a one-off migration before we can consider adding support to search for highlights. **Note that the migration is not included in this work.**
Seems to work well and pass the changes to the StorageManager tests I made. 
This will also affect the schema porting work in #429, which I'll need to go over some more with these changes.
One unrelated thing that I discovered while playing with this fix was that the internally used `_index` flag, added to field definitions by the registry module if they have a corresponding index, was redundant. …
=> StorageManager fix for indexed text fields indexing the wrong field

src/search/search-index-new/storage/manager.ts, src/search/search-index-new/storage/types.ts
Sometimes it's useful to get the assoc. PKs with the suggestions returned from StorageManager's `suggest` method. This adds a flag to enable that. Noted that this was needed in particular for @subrat-sahu's custom-lists work during review
Currently returns an array of 2-element key value pair arrays of PKs => suggestion, i.e., `[PKType, string][]` if `suggestPks` flag is set, else simply `string[]`. 
Maybe there's a nicer way to type this return value though. Maybe an object of shape `{ suggestions: string[], pks?: any[] }` would provide a more consistent type (callers wouldn't have to add type guards or casts) and assume array lengths and orders are the same? @ShishKabab any suggestions/ideas?
Also added missing typings for `suggest` method.
=> StorageManager: add support for opt. PKs with `suggest` results

.package-exclude.lst, build/plugins.js, package-source-code.sh, package.json
- updated packaging build from using `zip` command to using `git archive`
- `zip` is less portable and realized we were excluding some important hidden config files by default, like `.babelrc`
- `git archive` should include all files that are included in git, and exclude those in `.gitignore` (hence no need for the separate excluded files list anymore)
=> Move to using `git archive` for zipping source code

src/custom-lists/Readme.md, src/custom-lists/background/storage.test.js, src/custom-lists/background/storage.test.ts, src/custom-lists/background/storage.ts, src/overview/actions.js, src/search-filters/Readme.md, src/search-filters/container.js, src/search/search-index-new/search/index.ts
- Add Readme for custom-list module.
- wrote tests for nearly all the background functions.
- Add Readme for new search filter module.
- Open sideber in filter mode if filter is initiated from any search bar.
- Remove tag from filters if no page is associated with it.
- Add Readme for `src/overview/sidebar-left` module.
- More tests.
=> Tests and Readme for custom-lists module

package.json, src/blacklist/background/interface.js
- this bug has been around for a long time, but only just noticed it today when i went to blacklist a URL with parens
=> Hotfix for blacklist not working with URLs with parentheses

src/sidebar-overlay/components/Ribbon.css
It was the website's css overriding the iframe's width attribute.
=> Fixes iFrame covering up most of the page in some websites.

package.json, src/sidebar-overlay/components/Annotation.css, src/sidebar-overlay/components/CrowdfundingBox.css
- the rule removed the bottom margin, however it was doing it for every paragraph due to the selector used
- because it is part of the content script, it gets injected into every page and tries to override every <p> tag
- **good example of why tag selectors shouldn't be used** (classes should be safe with CSS modules)
- should fix #569 
- @oliversauter we should try to get this fix out ASAP as it would interfere with a lot of sites' styles
=> Remove <p> tag selector rule in content script styles

package.json, src/sidebar-overlay/content_script/interactions.js, src/util/transform-page-html.js
- because it's super slow going through every single element on the page and checking their styles in linear time
- addresses #612
- set this up as a hotfix branch, as I thought it would be nice to get it in ASAP but simple to convert into a feature branch if desired (@oliversauter)
=> Remove hidden HTML element filter

src/sidebar-overlay/components/Ribbon.js
- the `openSidebar` method wasn't actually returning a `Promise`, although all invoking code treated it as if it did
- should fix #618
- regressed in e6693cfdc86309b7bd1c1e5249eee1f656cec861
=> Wait for sidebar to setup before attempting annot scroll

src/direct-linking/content_script/annotations/dom-highlight-range.ts, src/direct-linking/content_script/annotations/index.js
Fixes #600 
- Changed the usage of `span` tag to create highlights. Now a custom tag `memex-highlight` is being used.
- Nodes consisting entirely of whitespace are not being highlighted anymore. This proves useful in not breaking any table layouts.
=> Fix highlighting bug that broke layout/styling

src/common-ui/components/IndexDropdown.css, src/common-ui/components/IndexDropdown.js, src/common-ui/containers/AddListDropdownContainer.js, src/common-ui/containers/AddListDropdownContainer.tsx, src/common-ui/containers/IndexDropdown.tsx, src/custom-lists/background/index.js, src/custom-lists/background/storage.ts, src/popup/collections-button/actions.ts, src/popup/collections-button/reducer.ts, src/popup/container.tsx, src/popup/tags-button/actions.ts, src/popup/tags-button/reducer.ts
**Old behavior:** When a user had to add a tag to a page, and add the page to a collection, they had to reopen the popup to do so.
**New behavior:** Wait for it...
**Old behavior:** Typing into the searchbar and clearing it means losing suggestions.
**New behavior:** Predictable and intuitive like many other applications.
Demo shows the working of Tag popup menu. Collection popup menu works similarly.
=> Add a 'Back button' for Tag and Collection popup

src/content-tooltip/content_script.ts, src/sidebar-overlay/content_script/interactions.js, src/sidebar-overlay/content_script/rendering.ts, src/toolbar-notification/content_script/rendering.ts
Fixes #645
Sidenote: Changed `browser.extension.getURL` to `browser.runtime.getURL` as it is stated as "deprecated" on MDN.
=> Critical fix for no ribbon on FF

src/activity-logger/background/tab-state.ts, src/popup/tooltip-button/actions.ts, src/sidebar-overlay/components/Ribbon.js, src/sidebar-overlay/components/index.js, src/sidebar-overlay/content_script/index.ts, src/sidebar-overlay/content_script/interactions.js
- When the user toggles the tooltip/ribbon on/off from the popup, the ribbon (if it has already been inserted), does not update itself to show the same change. It shows the previous values that it got when the ribbon was loaded into the DOM.
- When the same is done through the ribbon, other ribbons present on other tabs do not show the change either.
Created an RPC to update the state of the ribbon on tab change as well as through popup. 
- Reorganized methods and declarations in the file `interactions.js` in order to keep the most important ones first.
- Added/updated comments.
- Fix a bug that caused an error to be thrown whenever ribbon was closed via the little 'x' due to not handling the event propagation properly.
=> Allow updating Ribbon's state on tab change

package.json, src/activity-logger/background/tab-change-listeners.ts, src/activity-logger/background/types.ts, src/util/ui-logic.test.ts
Noted a flaw in the implementation of the last attempt to "throttle" page and fav-icon indexing: it was creating a single debounced fn which all tabs were competing for. This results in tabs being completely missed when opening multiple tabs within certain time thresholds.
- the throttle is still wanted due to high frequency changes with tab URL and favIconUrl props
- now it has been updated to work on a per-tab basis where there is a throttled (not debounced) fn for each tab
- fixes #640 
1. easy way on Chrome via bookmarks manager:
i. make a large number (8+) of discrete bookmarks in a single dir
ii. open `chrome:bookmarks`
iii. right click on that dir and press "Open all bookmarks"
iv. wait for all tabs to load
v. focus each tab, one-by-one (only need to keep focused a few 100ms)
vi. …
=> Move flawed debounced indexing to throttle-per-tab

package.json, src/common-ui/containers/IndexDropdown.tsx, src/popup/components/Popup.css, src/sidebar-common/annotation-box/edit-mode-content.tsx, src/sidebar-common/comment-box/components/comment-box-form.tsx, src/sidebar-overlay/store.ts
- addresses #722
- overrides default `keydown` event handling in a hacky way, but it seems to make things work again from user POV which I feel is the main thing for now
- does this break anything? (@oliversauter if you have time, it would be good to get your feedback testing this)
- @ShishKabab @digi0ps @mohitsakhuja it would be great to get your thoughts on this issue, this quick hack, and ways to address it in the long-term (I had one idea in this comment, but not sure if I'm on the right track: https://github.com/WorldBrain/Memex/issues/722#issuecomment-465845828)
=> Add hack to allow users to still add annot comments, tags

package.json, src/overview/results/components/search-type-switch.css, src/search-injection/components/ResultItem.css, src/search-injection/components/Results.css, src/search/background/annots-list.ts, src/search/background/page-url-mapper.ts, src/search/background/storage.ts, src/search/background/utils.ts
@oliversauter So I tracked down the bottlenecks in the search where it was spending most of the time. As said on slack, this was the post-search stages where display data is mapped to the results. 
To get a better idea, here's roughly how those stages are set up:
page search: 
1. UI script remote call **(super fast)**
2. search stage **(fast)**
3. page display data mapping stage **(slow)**
4. return result to UI script **(super fast)**
annots search:
1. UI script remote call **(super fast)**
2. search stage **(fast)**
3. page display data mapping stage **(slow)**
4. annots display data mapping stage **(super slow)**
5. return result to UI script **(super fast)**
They're pretty similar pipelines, apart from extra stage in annots search.
stage 3 and annots search stage 4 have been optimized …
=> Hotfix 0.16.1

src/options/settings/keyboard-shortcuts.ts, src/sidebar-overlay/ribbon/components/ribbon.tsx
Tooltip for  **Open Sidebar**  now displays the correct shortcut.
Open/close Sidebar seems to be more complex than just a toggle. The shortcut in the settings only opens the Sidebar so changed the text from **Toggle** to **Open**.
=> open sidebar tooltip

build/loaders.js
If `mode` is equal `development` we add a hash using path + local + base64:5
eg. `src-overview-results-components-__main--dzcJi`
Solving the #418 issue.
=> hotfix(css-module): Use localIdentName to identify className on development

src/options/options.jsx
Uncomment validation of NODE_ENV on `options.jsx`
Now DevTools is required on dev mode is running
=> Chore(dev-tools): Enable Devtools on Dev mode

src/background-script/index.ts, src/background.ts, src/content-tooltip/components/container.jsx, src/content-tooltip/interactions.ts, src/custom-lists/background/index.ts, src/custom-lists/background/storage.test.ts, src/custom-lists/background/storage.ts, src/options/store.js, src/popup/components/Button.css, src/popup/store.ts, src/popup/tooltip-button/actions.ts, src/popup/tooltip-button/components/TooltipButton.tsx, src/search/background/annots-list.ts, src/search/models/page.ts, src/search/on-demand-indexing.ts, src/sidebar-overlay/ribbon-sidebar-controller/ribbon-sidebar-container.tsx, src/sidebar-overlay/ribbon/actions.ts, src/sidebar-overlay/ribbon/components/ribbon-container.tsx, src/sidebar-overlay/ribbon/components/ribbon.tsx, src/sidebar-overlay/ribbon/types.ts, src/util/raven.ts, src/util/storage-changes.test.ts, src/util/storage-changes.ts
Includes fixes for:
- [adding non-indexed pages to collections not being indexed on-demand](https://www.notion.so/worldbrain/Bugfixing-Marathon-b4b0b75688414f48978c7375ee57a388?p=7cd09f7be828459a87cb081e409f4b64): doc also talks about the same issue with tagging, however that seems to have been already fixed
- [restored annots not showing up in blank terms searches](https://www.notion.so/worldbrain/Bugfixing-Marathon-b4b0b75688414f48978c7375ee57a388?p=0b1767119f974ae3aa43751383abe29f): annot search assumed that no annotations could be created before the ext install time, thus don't bother searching back further. However, with the restore feature, there can indeed be annotations in the DB created before the ext was installed!
- [unifying of tooltip and highlights states + related new …
=> Misc hackday tasks

GETTING-STARTED.md
In response to the build failures that popped up recently, I've updated the installation note to mention Node 10.x as a requirement, as opposed to the latest Node LTS which recently changed from 10 -> 12
=> Updated installation requirements from Node LTS -> Node 10.x

src/direct-linking/content_script/annotations/anchoring/LICENSE, src/direct-linking/content_script/annotations/anchoring/range.coffee, src/direct-linking/content_script/annotations/anchoring/util.coffee, src/direct-linking/content_script/annotations/anchoring/xpath.coffee
I was excited to see my own code still included here. Thanks for putting these projects to good use!
I did not see any license from the Hypothes.is code, though, so I thought I'd help out by adding it. I noticed that the Annotator license text was added to the top of those files, though it wasn't in the originals. Rather than maintaining the license headers in all these files, and considering that the files from both projects are co-mingled in a single sub-directory, I created a separate `LICENSE` file for that sub-directory containing the original licenses with the World Brain copyright notices appended to copyright of each.
I hope it helps!
Commit message follows:
Extract the license headers added to the Annotator project files into a
separate LICENSE file in the directory containing …
=> Include Annotator and Hypothes.is licenses

src/sync/background/index.test.ts
This PR enables the sync logging at the end of the pre sync step, meaning that any changes the user makes while executing the initial sync (like making a bookmark) are eventually synced. [It's built on this PR](https://github.com/WorldBrain/Memex/pull/907).
The test for this was written in a commit that already landed in develop, but it's in `sync/background/index.test` and called:
```
should log and transfer changes made during initial sync from ext to app
```
Can anyone come up with ways this might go wrong? For the initial version, we're only taking 2 devices into account. Work on 3+ device sync will start after these two PRs are merged.
One case I took into account is the object sent through the initial sync ending up in the sync log, which we don't want in the case of 2 devices (but …
=> Write changes made while execute initial sync, to sync log

src/sync/background/index.test.ts, src/sync/background/index.ts
Didn't test in browser with Firebase yet, but this should solve the error about not being able to sync without a user on startup, caused by the Firebase auth layer not immediately knowing whether the user is logged in on startup. It now waits for Firebase to realize there's already a user, with a timeout of 2 seconds.
=> Fix sync on startup

src/content-tooltip/components/container.jsx, src/content-tooltip/constants.js, src/content-tooltip/content_script.ts, src/content-tooltip/interactions.ts, src/content-tooltip/types.ts, src/content-tooltip/utils.ts, src/content_script.js, src/options/settings/components/keyboard-shortcuts-container.tsx, src/options/settings/keyboard-shortcuts.ts, src/sidebar-overlay/comment-box/components/comment-box-container.tsx, src/sidebar-overlay/content_script/index.ts, src/sidebar-overlay/content_script/ribbon-interactions.ts, src/sidebar-overlay/index.tsx, src/sidebar-overlay/ribbon-sidebar-controller/ribbon-sidebar-controller.tsx
This WIP PR is aiming to fix:
This also touches on 
And potentially other complexities due to the annotation actions and state are doing different things in different places.
I feel ideally there would be one redux state for the page that updates annotaions, changes to this state should be relfected by both annotations on the page and in the sidebar list. Though the scope of this change is unknown at this point pending the next set of investigation and refactoring in persuit of fixing this issue.
=> [WIP] Fix annotation states (amoung shortcut keys and sidebar, and other)

src/backup-restore/background/backend/google-drive/index.ts, src/backup-restore/background/backend/google-drive/token-manager.ts, src/backup-restore/background/index.ts, src/backup-restore/background/redirect.ts, src/backup-restore/ui/backup-pane/container.logic.test.ts, src/backup-restore/ui/backup-pane/container.logic.ts, src/util/tests/local-storage.ts, src/util/webextensionRPC.ts
Turns out that also when testing manually, the backup flow seemed to be broken, as it took me to the overview right after Google Drive login. I've fixed this and verified manually the flow works both with GDrive and the local server.
However, for some reason I don't get an access token anymore, maybe because of the hack we did (Google probably doesn't like two requests coming in.) This means I couldn't fully test GDrive backup/restore.
I'll now investigate this and fix it in this PR if possible.
=> Fix backup and restore flows

src/sidebar-overlay/sidebar/components/lists-container.js
Due to the form field's submit firing twice in rapid succession. Fixed by stopping propagation of the event.
=> Fix collections being added twice in the sidebar filter pane

src/authentication/components/AccountInfo.tsx, src/authentication/components/AccountMenu.tsx, src/authentication/components/Subscription/SubscriptionOptionsChargebee.tsx
This PR adds back into the extension the ability to 'Manage Existing Subscriptions' rather than needing to be redirected to the website. 
Needs a seccond test by someone other than me :)
=> Re-instate Managing Existing subscriptions via the extension

src/activity-logger/background/log-page-visit.ts, src/activity-logger/background/tab-change-listeners.ts, src/page-analysis/background/content-extraction/extract-html-content.ts, src/page-analysis/background/content-extraction/extract-pdf-content.ts, src/page-analysis/background/content-extraction/index.ts, src/page-analysis/background/fetch-page-data.ts, src/page-analysis/background/index.ts, src/page-analysis/extract-page-content.test.ts
On page visit, first a page stub is written to the database (URL and favicon only) and then after a timeout, the rest of the page is indexed. This would involve two page analysis invocations, which are quite expensive CPU-wise and involve an RPC call. This PR fixes this by only analyzing the page once, then re-using that result when indexing the full page.
I've tested the default prefs of indexing pages after 5 seconds. What are the other cases that need to be tested? I can see in the code that there might be a case where even stubs are not indexed, which should also be faster now.
=> Don't extract page content twice

src/bookmarks/background/types.ts, src/overview/results/actions.ts, src/overview/results/components/ResultListContainer.tsx, src/page-indexing/background/index.ts, src/search/bookmarks.ts, src/search/types.ts, src/sidebar-overlay/sidebar/components/result-list-container.tsx
- addresses bug described in my comment in https://github.com/WorldBrain/Memex/pull/958#issuecomment-593201641
- previously was passing the already normalized `url` field to it, which resulted in attempting an XHR on the ext's URL concat'd with the normalized URL (we throw away the protocol part in our normalization logic)
=> Ensure page `fullUrl` passed to needed overview XHRs

src/search-injection/constants.js, src/search-injection/utils.test.js
A duckduckgo search results URL does not always start with `?q=...`, especially not when coming from a page other than duckduckgo.com (for example when using certain browsers' search bars). This PR changes the URL detection regex string to work with any order of URL parameters.
=> Extend Regex for duckduckgo URL detection

src/common-ui/components/Checkbox.css, src/common-ui/components/Checkbox.tsx, src/options/settings/components/keyboard-shortcuts-container.tsx, src/options/settings/keyboard-shortcuts.ts
- previously checkboxes had the same styles when not disabled and the assoc. key shortcut recording input didn't get disabled
- now new styles assigned to the custom rendered checkbox when the underlying input is disabled + key shortcut recording input is disabled when corresponding checkbox is
=> Properly style dependent keyboard shortcut checkbox

src/manifest.json
It defaults to the current value `true` on Chromium anyway, and it isn't supported by all web browsers, see:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/offline_enabled
=> Removed `offline_enabled` from manifest

src/backup-restore/ui/backup-pane/panes/overview.tsx, src/common-ui/components/result-item.css
Just a tiny issue.
I only noticed this when accessing Memex from a different computer than i normally do, however they are both OSX and running latest chrome.
Issue: When a page title has an emoji in it, scroll bar would appear due to there being a fixed height set on title. 
I'm guessing for some reason this new computer has slightly different emoji rendering. Fixed by making title not a fixed height but have a min height. Height could also be removed but maybe there as a reason 26px had been set.
Also fixed a typo i noticed with the Backup help text.
=> Emojis in page titles wont create scroll bars any more

src/search/background/page-url-mapper.test.data.ts, src/search/background/page-url-mapper.test.ts, src/search/background/page-url-mapper.ts, src/sync/background/index.test.ts
- adds another DB query for the results of a terms search to get their bookmark status
- test added to ensure results from terms and non-terms searches are the same when all terms appear in all results
=> Fix pages found via terms searches losing their bookmark status

src/authentication/README.md, src/authentication/background/index.ts, src/authentication/background/setup.ts, src/background-script/setup.ts, src/job-scheduler/background/index.ts, src/job-scheduler/background/job-scheduler.test.ts, src/job-scheduler/background/job-scheduler.ts, src/job-scheduler/background/types.ts, src/tests/background-integration-tests.ts
This PR registeres an alarm with the extension alarm API via our job scheduler, that runs on the user's subscription expiry date if they are logged in, so that any changes (renewal or not) are correctly picked up and updated to the user object. The alarm is registered on a change of the user object itself, so e.g. on logins or purchases.
Also refactored our JobScheduler slightly to extract the init of jobs and the handling of jobs apart to better reason about these different types of job (fire one in the future, fire repeatedly, etc.)
=> Refresh the user's subsciption if they are logged in and it expires

src/activity-logger/background/index.ts, src/activity-logger/background/log-page-visit.ts, src/background-script/setup.ts, src/page-indexing/background/storage.ts, src/storage/middleware.ts
On every page visit, all visit object were read from the database, only to check if the last visit was more than X ago. By removing use of the Page model, these and some other queries are replaced by simpler, more direct and less expensive alternatives.
=> Fix excessive visits reading

src/content-scripts/content_script/ribbon.ts, src/content-scripts/content_script/sidebar.ts
In this pull request I set up the shadow DOM and CSS as soon as the ribbon/sidebar loads. In develop, I still see a lag for the ribbon, but not the sidebar. The lag for the ribbon is only a slight delay in loading the icons, but the ribbon itself is instantly in place.
=> Ribbon and sidebar should eagerly load CSS

src/background-script/setup.ts, src/custom-lists/background/storage.ts, src/storex-hub/background/index.ts, src/storex-hub/background/types.ts
As described by the title. Extra arg added to `indexPage` is `lists?: number[]`. CLI example:
```
yarn cli calls:execute io.worldbrain.memex indexPage '{"url": "https://en.wikipedia.org/wiki/Genome", "bookmark": true, "tags": ["tag-one", "tag-two"], "lists": [1591267315220]}'
```
Tested and works  :)
=> Allow remote apps to add page to lists while indexing a page

src/search/background/pages.test.ts, src/sync/background/index.test.ts, src/sync/background/sync-logging.ts, src/sync/index.tests.ts, src/tests/background-integration-tests.ts, src/tests/integration-tests.ts
=> Sync less data

src/background.ts
Call `navigator.storage.persist()` on startup after setting up storage. We're unsure whether this is necessary because of permissions asked in `manifest.json`, but the hope is to get less data evictions by the browser. I've done this in Memex instead of the Dexie back-end so we can `await` for this call before setting up the rest of the extension.
=> Explicitly tell browser to persist storage

package.json, src/overview/search-bar/actions.ts, src/overview/search-bar/constants.ts, src/overview/search-bar/index.test.ts, src/overview/search-bar/utils.ts, src/search/query-builder.js
This hotfix finishes the unfinished tasks from last hotfix #1071, adding support for tags with spaces in search bar filter hashtag syntax.
This is ready for testing
=> Hotfix/2.2.5 - filter tags with spaces

package.json, src/page-analysis/page-metadata-rules.ts, yarn.lock
Fixes #1096 
There were some API changes since v1.0.0, particularly commit mozilla/page-metadata-parser@920b786.
=> Update page-metadata-parser to v1.1.4

src/highlighting/ui/highlight-dom-range.ts, src/highlighting/ui/styles.css, src/util/computed-styles.test.ts, src/util/computed-styles.ts
Addresses #885
This makes sure that the text color of highlights can be read on websites that use dark mode. The value for determining whether or not the website qualifies as "dark" is more or less arbitrary, so suggestions on how to make that better would be great!
Before
After
=> Improve highlight readablity for dark mode websites

src/activity-streams/background/index.ts, src/background-script/setup.ts, src/background.ts, src/content-scripts/background/index.ts, src/content-sharing/background/index.test.ts, src/content-sharing/background/index.ts, src/copy-paster/background/index.ts, src/copy-paster/background/template-data-fetchers.ts, src/tests/background-integration-tests.ts, src/tests/integration-tests.ts, src/tools/storage-explorer.ts
This integrates the activity stream infrastructure available so far and subscribes users to the pages (which includes annotation replies) of content they upload. As a result, they can follow all discussions on their own content.
There was a bug in the Storex core package, the collection registry, that prevented a relation to be the PK, which is the case with the homeFeedInfo (containing the timestamp of when the activity feed was last checked.) This was fixed, along with the needed fix to go along with it in the Firstore backend. It would be good if somebody else could also look at it to prevent stupid errors.
=> Subscribe to sharedPageInfo stream whenever ensuring page info

src/annotations/background/index.ts, src/background-script/quick-and-dirty-migrations.ts, src/content-scripts/content_script/global.ts
In researching refactoring approaches for multi-content IDs and `normalizedURL` I came across an issue here where annotations were not beings saved with their normalisedUrl (instead using their full url). 
Annotations used to be saved using their normalised url so I'm assuming that's the desired affect here, although this isn't documented.
Seemed to have been introduced with recent clean up to some of the old annotation code, and missed due the the multiple code paths. Postmortom of the bug: mainly due to the known normalisedUrl inconsistencies, exasberated by the lack of types and tests in this part of the code.
In this PR I've fixed it in two places
- Supplying the `getNormalizedPageUrl()` to the pageUrl instead of the fullUrl, it doesn't seem like the fullUrl is wanted here. 
- Making …
=> Fix bug in creating annotations where url ids would not be normalised.

src/background.ts, src/content-scripts/content_script/global.ts, src/content-scripts/content_script/ribbon.ts, src/content-scripts/content_script/sidebar.ts, src/options/options.jsx, src/popup/index.tsx, src/util/rpc/rpc.ts, src/util/webextensionRPC.ts
Switched out the underlying message pasing mechanism between content
scripts and background page to use Runtime.onConnect and exchange
messages over specific ports rather than one global channel.
Was needed to fix issues when using multiple extension pages, like for
the PDF Viewer. Also should improve understandability and extensibility
in the long term.
some global state and much legacy still remains in the approach to
remote functions. It's not within this scope to refactor it all at this
time, but is hopefully another step in the right direction.
=> RPC Refactor - New Port based transport layer

src/storage/server.ts, src/tests/background-integration-tests.ts
Due to wrong assumptions in how the tests set up the mocked server storage, the application layer was also used in the tests. Fixed here.
=> Skip application layer in tests

src/backup-restore/background/index.ts, src/backup-restore/background/types.ts, src/common-ui/components/design-library/actions/PrimaryAction.tsx, src/personal-cloud/background/index.ts, src/personal-cloud/ui/components/data-dumper.tsx, src/personal-cloud/ui/components/data-migrator.tsx, src/personal-cloud/ui/components/shared-components.tsx, src/personal-cloud/ui/onboarding/logic.test.ts, src/personal-cloud/ui/onboarding/logic.ts, src/storage/passive-data-wipe.test.ts, src/storage/passive-data-wipe.ts
Included:
- Passive data deletion logic adapted from @cdharris snippet on https://www.notion.so/worldbrain/Clean-existing-data-before-while-migrating-data-to-cloud-cc840cbca1b54c139b670a6710740a41
- DB change recording for backups disabled prior to executing passive data deletion
Not included, but part of the specs:
- Setting the extension install time key based on the oldest visit. Didn't do this as we still haven't gotten around to the move to the new settings collection. Unsure if this data should be moved to that collection or kept in local storage.
=> Add in passive data deletion to existing-user cloud onboarding

docs/Writing-React-Components.md
Warning the guide is out of date at the top, suggesting an example in the codebase instead.
=> Guide out of date. Example in the codebase
