src/activity-logger/background/index.js

Adds debouncing to indexing of a page for each tab. (waits for 10s before indexing)

Fixes indexing of web apps.

---

src/overview/components/DateRangeSelection.jsx

This is a small bug fix that fixes issue explained in #33.

Fixes setting date when clicking outside the date picker. Closes #33.

---

src/omnibar.js

Looks a bit different from the Research-Engine version but serves the purpose

Added time icon in omnibar search results

---

src/omnibar.js

Found the solution @ Webmex, We can thank them

fixed getBrowserInfo() error

---

src/options/imports/components/Import.css

Fix https://github.com/WorldBrain/WebMemex/issues/78

Fix styling issue on import page

---

package-lock.json
src/activity-logger/background/index.js
src/omnibar.js
src/overview/components/PageResultItem.jsx

Added base64 encoding to the Url's

Url encoding(hashing)

---

src/overview/base.css
src/overview/components/DateRangeSelection.css
src/overview/components/Overview.css
src/overview/overview.html
src/popup/components/Button.css
src/popup/components/Popup.css
src/popup/popup.html

Fix issue https://github.com/WorldBrain/WebMemex/issues/114

Style inconsistencies in Firefox - fix issue #114

---

Licence
Readme.md
docs/Contributing-Guide.md
docs/How-It-Works.md
docs/Readme-Template.md
src/options/privacy/index.jsx

Trying to make the onboarding process as well as the general docs easier to understand and more concise. Feedback is most definitely welcome! 
**TO DO**

New Onboarding Process

---

src/search/query-builder.js
src/util/transform-page-html.js
src/util/transform-page-text.js

Via suggestions from @oliver: Removing single digits and digits over 5+ characters, Removing 20+ character words, removing words with 4 consonants in a row, combing words separated by -, removing 'svg', 'code', 'select' 'display: none' and 'visibility: hidden'.

Updated pipeline

---

src/bookmarks/background/deletion.js
src/bookmarks/background/index.js
src/search/index.js
src/search/search-index/add.js
src/search/search-index/del.js

Unbookmarking logic for bookmarks removal event

---

src/util/transform-page-text.js

- Tested w/ Chinese, Japanese, Korean, Russian, Hindi and Arabic
@oliversauter Do you want to test this and or test with more/other languages or can I pull this?

Fixed the removal of Cyrillic characters

---

src/page-analysis/background/index.js
src/page-analysis/background/make-screenshot.js

Added simple html5 canvas functionality to resize images.
Not sure where to find how much this affects the size of the stored images?
Currently maintaining aspect ratio and making the images a max of 400x400. 
This can be played around with in regards to quality and size

Resize Screenshots

---

src/background.js
src/util/filter-params.js
src/util/url-filter.js

*Do Not Merge*
As discussed in issue #112

Added URL Filter Module

---

src/manifest.json
src/options/new-install/index.jsx
src/options/new-install/styles.css
src/options/options.html
src/options/tutorial/index.jsx
src/options/tutorial/style.css
src/overview/overview.html

Last changes before we can push it to the grid!

Update after user testing in café

---

src/util/transform-page-html.js

Fix span doesn't produce space

---

src/options/imports/components/DownloadDetails.css
src/options/imports/components/DownloadDetails.jsx
src/options/imports/components/Import.css
src/options/imports/components/ProgressBar.jsx
src/options/imports/components/ShowDownloadDetails.jsx
src/options/imports/components/StatusReport.jsx
src/options/imports/container.jsx
src/options/imports/reducers.js
src/options/imports/selectors.js
src/popup/constants.js
src/popup/container.js

Add the Failed List into progress view

---

src/popup/container.js

I just remove the UI from popup script. did not remove the functions related to it because we will use these functions in future.

Remove the un/bookmark button from popup

---

src/activity-logger/background/log-page-visit.js
src/bookmarks/background/addition.js
src/popup/container.js
src/search/index.js
src/search/search-index/add.js

Improve popup bookmarking button on new/deleted pages

---

src/common-ui/components/LoadingIndicator.jsx
src/overview/actions.js
src/overview/components/PageResultItem.css
src/overview/components/PageResultItem.jsx
src/overview/container.js
src/overview/reducer.js
src/overview/selectors.js

- fixes #242; dispatch of new search request removed at end of async deletion logic
- also needed to add in missing "isDeleting" state (as it's async) and outcomes needed to be handled
- means the result stays rendered until the deletion is finished - for now gave it a slight fade and loading indicator for visual indication + disable buttons

Improve overview result deletion states

---

Readme.md

Fixed a few spelling mistakes and grammatical errors like missing comma or wrong usage of word.

Fixed: Spelling and Grammer Mistakes

---

src/overview/components/PageResultItem.css
src/overview/components/Tooltip.css
src/overview/filters/components/FilterPill.js
src/overview/filters/components/Filters.css

Fixes weird overview styling in FF

---

.gitignore
gulpfile.babel.js
package.json
src/background.js
src/manifest.json

Few publishing commands introduced + update version number to 0.2.1

Update Version to 0.2.1

---

CONTRIBUTING.md
Readme.md
src/options/settings/components/SearchInjection.js

- in prep for git flow adoption
- all refs to `master` updated to `develop`

Update contribution guide instructions for `develop` branch

---

src/activity-logger/background/index.js
src/activity-logger/background/tab-change-listeners.ts
src/activity-logger/background/util.ts
src/page-analysis/background/fetch-page-data.js
src/search/background/index.js
src/search/search-index-new/bookmarks.js
src/search/search-index-old/pipeline.js
src/util/encode-url-for-id.js

We installed sentry on the bg script in #381 and have got lots of new stuff coming in to fix. This addresses the most commonly encountered errors. Majority was expected errors we set up to be thrown from various modules but many we have just left uncaught.
*Should* fix:
- [No existing value exists for supplied timestamp ID: visit/1526275391456](https://sentry.io/worldbrain-ug/javascript/issues/554729589/)
- [No tab with id: x](https://sentry.io/worldbrain-ug/javascript/issues/554720452/)
- [Cannot convert undefined or null to object](https://sentry.io/worldbrain-ug/javascript/issues/554730189/)
- [URI malformed/Invalid URL](https://sentry.io/worldbrain-ug/javascript/issues/554728654/)
- [Tab URL changed before event occurred](https://sentry.io/worldbrain-ug/javascript/issues/554738272/) …

BG script fixes for some new sentry reports

---

CONTRIBUTING.md
Readme.md
package.json
src/analytics/analytics.js
src/background.js
src/manifest.json
src/options/acknowledgement/components/styles.css
src/options/base.css
src/options/blacklist/components/base.css
src/options/containers/settings/style.css
src/options/imports/components/Import.css
src/options/imports/components/Import.jsx
src/options/imports/enhancer.js
src/options/imports/reducer.js
src/options/privacy/components/Privacy.css
src/options/settings/components/SearchInjection.css
src/overview/components/tooltips.js
src/overview/constants.js
src/overview/enhancer.js
src/overview/filters/reducer.js
src/overview/filters/selectors.js
src/overview/onboarding/components/Onboarding.css
src/page-analysis/content_script/extract-fav-icon.js
src/search/background/index.js
src/search/search-index-new/models/fav-icon.ts
src/search/search-index-old/bookmarks/add.js
src/search/search-index-old/util.js

- forgot to do this
- dupe of #399

[dupe] Release 0.3.3

---

.storybook/config.js
.storybook/webpack.config.es6.js
.storybook/webpack.config.js
build/loaders.js
package.json
src/stories/index.js
yarn.lock

[Default setup](https://storybook.js.org/basics/guide-react/) which uses `create-react-app` webpack config gets the everything set up but postCSS doesn't work. 
Tried [custom setup](https://storybook.js.org/configurations/custom-webpack-config/) getting a few errors. Not able to resolve those errors, don't have much webpack config experience :|
Would be awesome, if this works out 🎉

Storybook setup.

---

src/search/search-index-new/storage/dexie-schema.ts
src/search/search-index-new/storage/manager.ts
src/search/search-index-new/storage/registry.ts
src/search/search-index-new/storage/types.ts

See following comment + commit message:
https://github.com/WorldBrain/Memex/pull/435#issuecomment-401674206
Moved into separate PR as this is higher prio to get into `develop` (would be good to get migration sorted before other branch merged)

Ensure non-indexed fields go through preprocessing

---

src/analytics/internal/analytics.js
src/analytics/internal/constants.js
src/analytics/internal/send-to-server/send-to-server.js
src/overview/onboarding/actions.js
src/util/generate-token.js

Added DNT support on the server by [this commit](https://github.com/WorldBrain/analytics-backend/commit/18df52aaf2d7c54bd11821aec2d02c2284d389f6)

Do not track in the extension

---

Readme.md

The URL of How it Works was not working .

Fixed README.md -> How it Works URL

---

src/sidebar-overlay/components/AnnotationContainer.js
src/sidebar-overlay/components/Ribbon.js

Fixes: 
- tag holder bug
- annotation content not loading
- annotation text minimising bug

Fixes for misc bugs.

---

build/minimizers.js
build/static-files.js
src/activity-logger/background/tab-manager.ts
src/activity-logger/background/tab-state.ts
src/sidebar-overlay/components/Ribbon.js

@poltak [continuation to slack discussion] This is the commit where I set the shouldRenderiFrame to true if it's not when clicking the Ribbon. As you can see a frame dependent function is being called next, which throws the error when the frame hasn't been loaded yet.

Set shouldRenderiFrame true conditionally true when opening sidebar.

---

src/common-ui/components/IndexDropdown.css
src/common-ui/components/IndexDropdownAnnotation.css
src/sidebar-overlay/components/Annotation.css

small fixes

---

src/sidebar-overlay/components/AnnotationContainer.js
src/sidebar-overlay/components/sidebarContainer.js
src/sidebar-overlay/redux/actions.js
src/sidebar-overlay/redux/reducer.js
src/sidebar-overlay/redux/selectors.js

Hotfix for annotations tag glitch while loading.

Annotation tags glitch

---

src/sidebar-overlay/components/Ribbon.js

- dupe of #502 but only with the relevant commit (that branch wasn't based on `master`, although it would be nice to get this fix rolled-out ASAP)

Quickfix for issue #496.

---

src/sidebar-overlay/CommentBox/components/CommentBox.js

Prevent focusing of CommentBox until Ribbon is pressed.

---

package.json
src/popup/container.js
src/sidebar-overlay/CommentBox/components/CommentBox.js
src/sidebar-overlay/components/Ribbon.js

Merge preferred via git flow client - opening for visibility.

Ribbon sidebar fixes

---

src/sidebar-overlay/components/Ribbon.css
src/sidebar-overlay/components/Ribbon.js

I have added some css attributes related to iFrame's dimensions to prevent global overrides. Sorry for the inconvenience caused @oliversauter.

Prevents global overrides for iFrame.

---

package.json
src/sidebar-overlay/components/Ribbon.css
src/sidebar-overlay/components/Ribbon.js

- contains @digi0ps fix from #528 
- fixes #525  
- updates ext version to 0.7.8

Fixes iFrame covering up most of the page in some websites

---

package.json
src/activity-logger/background/index.ts
src/activity-logger/background/tab-change-listeners.ts
src/activity-logger/background/tab-manager.ts
src/activity-logger/background/tab-state.ts
src/activity-logger/background/types.ts
src/content-tooltip/components/tooltip-states.jsx
src/manifest.json
src/popup/actions.ts
src/search/background/index.js
src/search/bookmarks.ts
src/search/index.ts
src/search/search/suggest.ts
src/search/tags.ts

- fixes #575 
- issue with tags and collections not loading seems to be reproducible if you open that part of the popup when the page is still loading (both new tab + new page load in an existing tab)

Popup state loading changes

---

src/sidebar-overlay/CommentBox/components/CommentBox.js

Add Shift+Enter keyboard shortcut to add comments

---

src/activity-logger/background/index.ts
src/activity-logger/background/tab-bridge.ts
src/activity-logger/background/tab-change-listeners.ts
src/activity-logger/background/tab-manager.ts
src/background-script/on-install-hooks.ts
src/sidebar-overlay/README.md
src/sidebar-overlay/components/AnnotationContainer.js
src/sidebar-overlay/components/Ribbon.js
yarn.lock

@poltak I tried to inject the whole content_script on all pages but it is not working somehow, I don't know why it is so. trying to resolve it soon.

Fix sidebar when extension updates

---

src/common-ui/containers/AddListDropdownContainer.js
src/common-ui/containers/IndexDropdown.tsx
src/custom-lists/components/overview/sidebar/Index.js

Fix : Support for emoji in collection naming

---

build/config.js
build/external.js
build/loaders.js

@poltak This should fix the build  :)

Fix TS loading of external packages

---

src/options/settings/components/SearchInjection.js

Fixed the broken link : "Help integrating them" in Settings.

#692 Fix broken link : "Help Integrating them" in Settings

---

src/dev/stories/index.js

#690 fix storybook file path bug

---

src/backup/background/backend/google-drive/index.ts
src/backup/background/backend/simple-http.ts
src/backup/background/backend/utils.ts

Did a quick test, seems to work. To be tested is whether GDrive backup still works.

Structure of local backup is now identical to GDrive backup

---

src/util/webextensionRPC.ts

Sidebar & tooltip was broken on firefox when #678 was merged.
https://github.com/WorldBrain/Memex/pull/678/commits/1dc86edecab2aaa86aa28c93d81bc73d32d97cce#diff-44cac06f3f6a4d4fae024ac443aa1844R76

Fix firefox errors

---

src/sidebar-overlay/ribbon/components/ribbon.tsx

Adding the "close ribbon once" button to the new ribbon.

Add close ribbon button back

---

src/common-ui/containers/IndexDropdown.tsx
src/sidebar-common/sidebar/components/menu-styles.ts
src/sidebar-overlay/ribbon/components/ribbon-container.tsx

Removed `isForAnnotation` from ribbon tags manager

Fix tags not being added to page from ribbon

---

src/common-ui/components/progress-step-container.tsx
src/common-ui/components/progress-step.css
src/common-ui/components/progress-step.tsx
src/overview/onboarding/components/next-step-button.css
src/overview/onboarding/components/onboarding-box.css
src/overview/onboarding/components/onboarding-step.tsx
src/overview/onboarding/components/search-settings.css
src/overview/onboarding/components/search-settings.tsx
src/overview/onboarding/screens/onboarding/index.tsx

Improved the size of things on smaller screens
Current step now has a different colour
Layout now uses flex box so we can keep the Next buttons aligned to the bottom
- ignore the height of the first getting started screen. WIP improving the design of that.

Improved styling

---

img/onboarding/backgroundBlob.svg
src/overview/onboarding/components/onboarding-box.css
src/overview/onboarding/components/onboarding-box.tsx
src/overview/onboarding/components/onboarding-step.tsx
src/overview/onboarding/components/search-settings.css
src/overview/onboarding/screens/onboarding/index.tsx

1 bug fix, 2 style tidy ups
and some code cleaning
- can replicate on really large monitors, the settings area becomes misaligned due to the flexbox settings and the way the min-width on the box was overriding the max-width and the white box was larger than is should have been.
I've made a min-height on the white boxes so that the next buttons are always in the same place (aligned flex-end to the bottom of the area)
I removed the blob graphic and white box on the landing screen. It was difficult getting the blob positioned right. Feeling like it looks better without it until we get something fancy (animated blob). Made the 'world' float (getting started screen).
+ removed some commented out code and tidied a few classes

Onboarding tidy up

---

src/authentication/background/index.ts
src/authentication/background/types.ts
src/authentication/background/utils.ts
src/backup/background/index.ts

add the remote function `isAuthorizedForFeature(feature: UserFeature) : boolean`

Authentication convenience feature - isAuthorizedForFeature

---

src/page-indexing/background/storage.ts
src/search/background/pages.test.ts
src/sync/background/index.ts
src/sync/background/sync-logging.test.ts
src/sync/background/sync-logging.ts

Sync optimizations

---

src/page-indexing/background/storage.ts
src/search/index.test.ts

Ensure no fields are written to page storage that don't belong in there

---

.gitmodules
package.json
src/background-script/setup.ts
src/storex-hub/background/index.ts
tsconfig.json
yarn.lock

This adds `bgModules.storexHub` which does nothing by default. But, if you call its `connect()` method (from the Developer Tools) it'll let you call Memex storage operations through Storex Hub.

First Storex Hub integration prototype

---

Readme.md

Less lengthy, cut down the readme to essentials. 
Added new roadmap and areas of contributions.

Update Readme to be more contributor friendly

---

src/backup-restore/ui/backup-pane/components/provider-list.jsx

This app is great! I'm super impressed!
This PR is just a small wording change I noticed while setting up the app.
Hopefully I'll be contributing a lot more in the future. Taking a look at other open issues I can help with now.
<3

Change wording

---

src/background-script/setup.ts
src/page-indexing/background/index.ts
src/search/bookmarks.test.ts

Adds a test to recent fix in #960

Write test for recent fix for passing fullUrl to bookmarks XHR

---

src/background-script/setup.ts
src/background.ts
src/sync/background/index.ts

Added Twilio as STUN and TURN servers. For this I needed to implement a Cloud Function generate Twilio tokens for us that I've deployed both in the staging and production Firebase projects. This needs to be tested by trying to sync in a setup that normally wouldn't allow it, and then testing this branch in that same setup.

Implement Twilio ICE servers

---

Readme.md

Hi, I'm making updates for Open Collective. Either you or another core contributor signed this repository up for Open Collective. This pull request adds financial contributors from your Open Collective https://opencollective.com/worldbrain ❤️
What it does:
- adds a badge to show the latest number of financial contributors
- adds a banner displaying contributors to the project on GitHub
- adds a banner displaying all individuals contributing financially on Open Collective
- adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website
P.S: As with any pull request, feel free to comment or suggest changes.
Thank you for your great contribution to the Open Source community. You are awesome! 🙌
And welcome to the Open …

Add Open Collective

---

src/common-ui/GenericPicker/components/SearchInput.tsx
src/custom-lists/ui/CollectionPicker/index.tsx
src/tags/ui/TagPicker/index.tsx

So far fixed issue #1016. Thanks for the report @kellective 
The other main thing to do so far is fix the failing test. I had a bit of a look at this one last Friday but couldn't work out exactly what's exactly wrong. I plan to have another look later today. 
Not sure if this is something that might be immediately obvious to you @cdharris ? CI log with the error for ref: https://travis-ci.org/github/WorldBrain/Memex/builds/681506426

Fix up some issues related to work on the pickers

---

docs/in-page-ui-arch.puml
src/content-scripts/content_script/global.ts
src/in-page-ui/ribbon/react/containers/ribbon-holder/logic.ts
src/in-page-ui/shared-state/index.ts
src/in-page-ui/shared-state/types.ts
src/in-page-ui/sidebar/react/containers/sidebar/index.tsx
src/in-page-ui/sidebar/react/containers/sidebar/logic.ts

Currently this PR just contains some small renaming and comments to help understand the existing InPageUI architecture.

Refactoring: In-Page-UI

---

src/content-scripts/content_script/global.ts
src/content-sharing/background/index.test.ts
src/content-sharing/background/index.ts
src/content-sharing/background/types.ts
src/in-page-ui/ribbon/react/containers/ribbon/logic.test.ts
src/in-page-ui/shared-state/shared-in-page-ui-state.ts
src/in-page-ui/shared-state/types.ts
src/overview/components/DashboardResultsContainer/logic.ts
src/sidebar/annotations-sidebar/containers/AnnotationsSidebarInPage.tsx
src/sidebar/annotations-sidebar/containers/logic.test.ts
src/sidebar/annotations-sidebar/containers/logic.ts
src/util/webextensionRPC.ts

Includes:
* Detecting sharing access changes in sidebar
* Unsharing an annotation upon deletion
* Removing annotation entries when removing a page from a list
@poltak I'm merging this now so your branch doesn't get too big to review. You can continue work on this branch though.

Jon's annotation sharing contributions

---

src/dashboard-refactor/lists-sidebar/components/list-item/ListItemBase.tsx
src/dashboard-refactor/lists-sidebar/components/lists-sidebar-item-with-menu/index.tsx
src/dashboard-refactor/lists-sidebar/components/lists-sidebar-item/index.tsx
src/dashboard-refactor/styleConstants.tsx
src/dashboard-refactor/styledComponents.tsx
src/dev/stories/dashboard-refactor/lists-sidebar/list-item.tsx

Can you double check the array type definition I used in the props?

Feature/dashboard refactor/lists sidebar item with menu

---

src/annotations/components/AnnotationEditable.tsx
src/authentication/background/index.ts
src/authentication/background/types.ts
src/background-script/setup.ts
src/common-ui/components/design-library/theme.ts
src/content-conversations/background/index.ts
src/content-conversations/background/types.ts
src/content-scripts/content_script/global.ts
src/dashboard-refactor/index.tsx
src/dashboard-refactor/logic.test.util.ts
src/dashboard-refactor/types.ts
src/dev/stories/dashboard-refactor/index.tsx
src/overview/components/Overview.tsx
src/services/content-conversations/index.ts
src/services/index.ts
src/services/types.ts
src/sidebar/annotations-sidebar/components/AnnotationsSidebar.tsx
src/sidebar/annotations-sidebar/containers/AnnotationsSidebarContainer.tsx
src/sidebar/annotations-sidebar/containers/logic.test.data.ts
src/sidebar/annotations-sidebar/containers/logic.test.ts
src/sidebar/annotations-sidebar/containers/logic.ts
src/sidebar/annotations-sidebar/containers/types.ts

Includes the conversation features for the followed collections sidebar UI, adding the ability to view and submit replies to shared annotations on those collections.

Conversations in sidebar
